apiVersion: v1
kind: ConfigMap
metadata:
  name: account-config
  labels:
    app: account-service
data:
  REDIS_HOST: redis-master.default.svc.cluster.local
  CASSANDRA_HOST: jdbc:cassandra://account-database:9042/
