apiVersion: v1
kind: Service
metadata:
  name: account-database # Sets service name
  labels:
    app: account-database # Labels and Selectors
spec:
  type: ClusterIP # Sets service type
  ports:
    - protocol: TCP
      port: 9042 # Sets port to run the application
      targetPort: 9042
  selector:
    app: account-database